<?php

/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

$dictionary['E2_properties'] = array(
    'table' => 'e2_properties',
    'audited' => true,
    'activity_enabled' => false,
    'duplicate_merge' => true,
    'fields' => array (
  'ent_propertietitle_txf' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_propertietitle_txf',
    'vname' => 'LBL_ENT_PROPERTIETITLE_TXF',
    'type' => 'varchar',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'ent_propertietype_ddw' => 
  array (
    'required' => true,
    'readonly' => false,
    'name' => 'ent_propertietype_ddw',
    'vname' => 'LBL_ENT_PROPERTIETYPE_DDW',
    'type' => 'enum',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => 'casa',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'ent_tipoPropiedad_list',
    'dependency' => false,
  ),
  'ent_floor_mlddw' => 
  array (
    'required' => true,
    'readonly' => false,
    'name' => 'ent_floor_mlddw',
    'vname' => 'LBL_ENT_FLOOR_MLDDW',
    'type' => 'multienum',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'calculated' => false,
    'size' => '20',
    'options' => 'ent_suelo_list',
    'default' => '',
    'dependency' => '',
    'isMultiSelect' => true,
  ),
  'ent_landsize_dec' => 
  array (
    'required' => true,
    'readonly' => false,
    'name' => 'ent_landsize_dec',
    'vname' => 'LBL_ENT_LANDSIZE_DEC',
    'type' => 'decimal',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'calculated' => false,
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 2,
  ),
  'ent_built_dec' => 
  array (
    'required' => true,
    'readonly' => false,
    'name' => 'ent_built_dec',
    'vname' => 'LBL_ENT_BUILT_DEC',
    'type' => 'decimal',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'calculated' => false,
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 2,
  ),
  'ent_width_dec' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_width_dec',
    'vname' => 'LBL_ENT_WIDTH_DEC',
    'type' => 'decimal',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'calculated' => false,
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 8,
  ),
  'ent_bottom_dec' => 
  array (
    'required' => true,
    'readonly' => false,
    'name' => 'ent_bottom_dec',
    'vname' => 'LBL_ENT_BOTTOM_DEC',
    'type' => 'decimal',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'calculated' => false,
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 8,
  ),
  'ent_shape_ddw' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_shape_ddw',
    'vname' => 'LBL_ENT_SHAPE_DDW',
    'type' => 'enum',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => 'regular',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'ent_forma_list',
    'dependency' => false,
  ),
  'ent_relief_ddw' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_relief_ddw',
    'vname' => 'LBL_ENT_RELIEF_DDW',
    'type' => 'enum',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => 'plano',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'ent_relief_list',
    'dependency' => false,
  ),
  'ent_state_ddw' => 
  array (
    'required' => true,
    'readonly' => false,
    'name' => 'ent_state_ddw',
    'vname' => 'LBL_ENT_STATE_DDW',
    'type' => 'enum',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => 'AGU',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'ent_mexicanStates_list',
    'dependency' => false,
  ),
  'ent_municipality_txf' => 
  array (
    'required' => true,
    'readonly' => false,
    'name' => 'ent_municipality_txf',
    'vname' => 'LBL_ENT_MUNICIPALITY_TXF',
    'type' => 'varchar',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'ent_colony_txf' => 
  array (
    'required' => true,
    'readonly' => false,
    'name' => 'ent_colony_txf',
    'vname' => 'LBL_ENT_COLONY_TXF',
    'type' => 'varchar',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'ent_street_txf' => 
  array (
    'required' => true,
    'readonly' => false,
    'name' => 'ent_street_txf',
    'vname' => 'LBL_ENT_STREET_TXF',
    'type' => 'varchar',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'ent_number_txf' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_number_txf',
    'vname' => 'LBL_ENT_NUMBER_TXF',
    'type' => 'varchar',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'ent_interior_txf' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_interior_txf',
    'vname' => 'LBL_ENT_INTERIOR_TXF',
    'type' => 'varchar',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'len' => '255',
    'size' => '20',
  ),
  'ent_code_int' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_code_int',
    'vname' => 'LBL_ENT_CODE_INT',
    'type' => 'int',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'len' => '5',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => false,
    'max' => false,
  ),
  'ent_reference_txa' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_reference_txa',
    'vname' => 'LBL_ENT_REFERENCE_TXA',
    'type' => 'text',
    'massupdate' => false,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'ent_agestatus_ddw' => 
  array (
    'required' => true,
    'readonly' => false,
    'name' => 'ent_agestatus_ddw',
    'vname' => 'LBL_ENT_AGESTATUS_DDW',
    'type' => 'enum',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => 'nuevo',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'ent_ageStatus_list',
    'dependency' => false,
  ),
  'ent_years_int' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_years_int',
    'vname' => 'LBL_ENT_YEARS_INT',
    'type' => 'int',
    'massupdate' => false,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'dependency' => 'equal($ent_agestatus_ddw,"usado")',
    'len' => '4',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => false,
    'max' => false,
  ),
  'ent_deliverymonth_ddw' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_deliverymonth_ddw',
    'vname' => 'LBL_ENT_DELIVERYMONTH_DDW',
    'type' => 'enum',
    'massupdate' => false,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => 'en',
    'calculated' => false,
    'dependency' => 'equal($ent_agestatus_ddw,"construccion")',
    'len' => 100,
    'size' => '20',
    'options' => 'ent_meses_list',
  ),
  'ent_deliveryyear_int' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_deliveryyear_int',
    'vname' => 'LBL_ENT_DELIVERYYEAR_INT',
    'type' => 'int',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'dependency' => 'equal($ent_agestatus_ddw,"construccion")',
    'len' => '11',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => 2022,
    'max' => false,
    'validation' => 
    array (
      'type' => 'range',
      'min' => 2022,
      'max' => false,
    ),
  ),
  'ent_informationplace_ddw' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_informationplace_ddw',
    'vname' => 'LBL_ENT_INFORMATIONPLACE_DDW',
    'type' => 'enum',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => 'si',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'ent_informacionLugar_list',
    'dependency' => false,
  ),
  'ent_levels_int' => 
  array (
    'required' => true,
    'readonly' => false,
    'name' => 'ent_levels_int',
    'vname' => 'LBL_ENT_LEVELS_INT',
    'type' => 'int',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'len' => '11',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => false,
    'max' => false,
  ),
  'ent_rooms_int' => 
  array (
    'required' => true,
    'readonly' => false,
    'name' => 'ent_rooms_int',
    'vname' => 'LBL_ENT_ROOMS_INT',
    'type' => 'int',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'len' => '11',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => false,
    'max' => false,
  ),
  'ent_bathrooms_int' => 
  array (
    'required' => true,
    'readonly' => false,
    'name' => 'ent_bathrooms_int',
    'vname' => 'LBL_ENT_BATHROOMS_INT',
    'type' => 'int',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'len' => '11',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => false,
    'max' => false,
  ),
  'ent_halfbathroom_int' => 
  array (
    'required' => true,
    'readonly' => false,
    'name' => 'ent_halfbathroom_int',
    'vname' => 'LBL_ENT_HALFBATHROOM_INT',
    'type' => 'int',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'len' => '11',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => false,
    'max' => false,
  ),
  'ent_parking_int' => 
  array (
    'required' => true,
    'readonly' => false,
    'name' => 'ent_parking_int',
    'vname' => 'LBL_ENT_PARKING_INT',
    'type' => 'int',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'len' => '11',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => false,
    'max' => false,
  ),
  'ent_roof_chk' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_roof_chk',
    'vname' => 'LBL_ENT_ROOF_CHK',
    'type' => 'bool',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => false,
    'calculated' => false,
    'size' => '20',
  ),
  'ent_service_ddw' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_service_ddw',
    'vname' => 'LBL_ENT_SERVICE_DDW',
    'type' => 'enum',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => 'si',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'ent_servicio_list',
    'dependency' => false,
  ),
  'ent_preservation_ddw' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_preservation_ddw',
    'vname' => 'LBL_ENT_PRESERVATION_DDW',
    'type' => 'enum',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => 'excelente',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'ent_preservacion_list',
    'dependency' => false,
  ),
  'ent_speech_txa' => 
  array (
    'required' => true,
    'readonly' => false,
    'name' => 'ent_speech_txa',
    'vname' => 'LBL_ENT_SPEECH_TXA',
    'type' => 'text',
    'massupdate' => false,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'ent_operation_mlddw' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_operation_mlddw',
    'vname' => 'LBL_ENT_OPERATION_MLDDW',
    'type' => 'multienum',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'calculated' => false,
    'size' => '20',
    'options' => 'ent_operacion_list',
    'default' => '',
    'dependency' => '',
    'isMultiSelect' => true,
  ),
  'ent_free_ddw' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_free_ddw',
    'vname' => 'LBL_ENT_FREE_DDW',
    'type' => 'enum',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => 'si',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'ent_libre_list',
    'dependency' => false,
  ),
  'ent_legal_txa' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_legal_txa',
    'vname' => 'LBL_ENT_LEGAL_TXA',
    'type' => 'text',
    'massupdate' => false,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'ent_price_dec' => 
  array (
    'required' => true,
    'readonly' => false,
    'name' => 'ent_price_dec',
    'vname' => 'LBL_ENT_PRICE_DEC',
    'type' => 'decimal',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'calculated' => false,
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 2,
  ),
  'ent_currency_ddw' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_currency_ddw',
    'vname' => 'LBL_ENT_CURRENCY_DDW',
    'type' => 'enum',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => 'mxn',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'ent_currency_ddw_list',
    'dependency' => false,
  ),
  'ent_cost_ddw' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_cost_ddw',
    'vname' => 'LBL_ENT_COST_DDW',
    'type' => 'decimal',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'calculated' => false,
    'len' => '18',
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 2,
  ),
  'ent_payment_ddw' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_payment_ddw',
    'vname' => 'LBL_ENT_PAYMENT_DDW',
    'type' => 'enum',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => 'contado',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'ent_pago_list',
    'dependency' => false,
  ),
  'ent_details_txa' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_details_txa',
    'vname' => 'LBL_ENT_DETAILS_TXA',
    'type' => 'text',
    'massupdate' => false,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
  ),
  'ent_commission_int' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_commission_int',
    'vname' => 'LBL_ENT_COMMISSION_INT',
    'type' => 'int',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'len' => '11',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => false,
    'max' => false,
  ),
  'ent_commission_ddw' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_commission_ddw',
    'vname' => 'LBL_ENT_COMMISSION_DDW',
    'type' => 'enum',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => 'si',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'ent_comision_list',
    'dependency' => false,
  ),
  'ent_sharecommission_int' => 
  array (
    'required' => true,
    'readonly' => false,
    'name' => 'ent_sharecommission_int',
    'vname' => 'LBL_ENT_SHARECOMMISSION_INT',
    'type' => 'int',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => '',
    'full_text_search' => 
    array (
      'enabled' => '0',
      'boost' => '1',
      'searchable' => false,
    ),
    'calculated' => false,
    'dependency' => 'equal($ent_commission_ddw,"si")',
    'len' => '11',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => false,
    'max' => false,
  ),
  'ent_currencycost_ddw' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_currencycost_ddw',
    'vname' => 'LBL_ENT_CURRENCYCOST_DDW',
    'type' => 'enum',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'default' => 'mxn',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'ent_mantenimiento_list',
    'dependency' => false,
  ),
  'ent_characteristics_mlddw' => 
  array (
    'required' => false,
    'readonly' => false,
    'name' => 'ent_characteristics_mlddw',
    'vname' => 'LBL_ENT_CHARACTERISTICS_MLDDW',
    'type' => 'multienum',
    'massupdate' => true,
    'hidemassupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'pii' => false,
    'calculated' => false,
    'size' => '20',
    'options' => 'ent_caracteristicas_list',
    'default' => '',
    'dependency' => '',
    'isMultiSelect' => true,
  ),
),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
    'full_text_search' => true,
);

if (!class_exists('VardefManager')){
}
VardefManager::createVardef('E2_properties','E2_properties', array('basic','team_security','assignable','taggable'));