<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN E2_properties
 */


class E2_properties_sugar extends Basic {
    public $new_schema = true;
    public $module_dir = 'E2_properties';
    public $object_name = 'E2_properties';
    public $table_name = 'e2_properties';
    public $importable = false;
    public $team_id;
    public $team_set_id;
    public $acl_team_set_id;
    public $team_count;
    public $team_name;
    public $acl_team_names;
    public $team_link;
    public $team_count_link;
    public $teams;
    public $assigned_user_id;
    public $assigned_user_name;
    public $assigned_user_link;
    public $tag;
    public $tag_link;
    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $description;
    public $deleted;
    public $created_by_link;
    public $modified_user_link;
    public $activities;
    public $following;
    public $following_link;
    public $my_favorite;
    public $favorite_link;
    public $commentlog;
    public $commentlog_link;
    public $locked_fields;
    public $locked_fields_link;
    public $sync_key;
    public $ent_propertietitle_txf;
    public $ent_propertietype_ddw;
    public $ent_floor_mlddw;
    public $ent_landsize_dec;
    public $ent_built_dec;
    public $ent_width_dec;
    public $ent_bottom_dec;
    public $ent_shape_ddw;
    public $ent_relief_ddw;
    public $ent_state_ddw;
    public $ent_street_txf;
    public $ent_number_txf;
    public $ent_interior_txf;
    public $ent_code_int;
    public $ent_reference_txa;
    public $ent_agestatus_ddw;
    public $ent_years_int;
    public $ent_deliverymonth_ddw;
    public $ent_deliveryyear_int;
    public $ent_informationplace_ddw;
    public $ent_levels_int;
    public $ent_rooms_int;
    public $ent_bathrooms_int;
    public $ent_halfbathroom_int;
    public $ent_parking_int;
    public $ent_roof_chk;
    public $ent_service_ddw;
    public $ent_preservation_ddw;
    public $ent_speech_txa;
    public $ent_operation_mlddw;
    public $ent_free_ddw;
    public $ent_legal_txa;
    public $ent_price_dec;
    public $ent_currency_ddw;
    public $ent_payment_ddw;
    public $ent_details_txa;
    public $ent_commission_ddw;
    public $ent_currencycost_ddw;
    public $ent_characteristics_mlddw;
    public $ent_saleprice_dec;
    public $ent_maintenancecostsale_dec;
    public $ent_currencysale_ddw;
    public $ent_currencymainsale_ddw;
    public $ent_detailssale_txa;
    public $ent_sharecommission_ddw;
    public $ent_sharecommission_dec;
    public $ent_commissionsale_dec;
    public $ent_commissionpre_dec;
    public $ent_sharecommissionpre_dec;
    public $ent_incomeprice_dec;
    public $ent_currencyincome_ddw;
    public $ent_currencymainpre_ddw;
    public $ent_aval_ddw;
    public $ent_deposit_ddw;
    public $ent_previewincome_ddw;
    public $ent_investigation_ddw;
    public $ent_restrictions_txa;
    public $ent_sharecommissionin_ddw;
    public $ent_sharecommissioninc_dec;
    public $ent_cost_dec;
    public $ent_maintenancecostinc_dec;
    public $ent_commissionincome_dec;
    public $ent_contract_ddw;
    public $ent_paymentsale_mlddw;
    public $ent_municipality_ddw;
    public $ent_colony_ddw;
    
    public function bean_implements($interface){
        switch($interface){
            case 'ACL': return true;
        }
        return false;
    }
    
}